language: android
android:
components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.0
      - android-25
before_install:
  - export LANG=en_US.UTF-8
  - nvm install 6
  - npm i -g ionic cordova
script:  
  - npm install
  - ionic platform add android
  - ionic cordova build android
