language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-23
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - export LANG=en_US.UTF-8
  - nvm install 6
  - npm i -g ionic cordova
install:
  - npm i
script:
  - ionic cordova build android
  - cordova build android
